# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b646118666937d3b7cf57b3e7fecfe8a585a1b303fd00aa5990a593a36c06ef400d87755beb57046c1e591f1a66d8fdd8e261da710ac4155e7ef8067712c9539

test:
  secret_key_base: 6c8edab00677b26b5317bdc8f0f5d240c21fc97b5f7698f245c94e7c20f1650f53cf2a9398c797c8a6e712e87011447cca512696b50e9896fca0748a11da6d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
